// GENERATED FILE - do not edit by hand. Run `npm run links:refresh`.
// Source: vote.gov (U.S. General Services Administration), data/states.json
//   https://raw.githubusercontent.com/usagov/vote-gov/staging/data/states.json
// Snapshot: 2026-10-03. Public domain (U.S. Government work).
import type { StateLinks } from './types';

export const STATE_LINKS_SNAPSHOT_DATE = '2026-10-03';

export const STATE_LINKS: Record<string, StateLinks> = {
  AK: {
    code: "AK",
    name: "Alaska",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.elections.alaska.gov/",
    register: "https://voterregistration.alaska.gov/",
    checkRegistration: "https://myvoterportal.alaska.gov/",
    moreInfo: "https://www.elections.alaska.gov/Core/voterregistration.php",
  },
  AL: {
    code: "AL",
    name: "Alabama",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.sos.alabama.gov/alabama-votes",
    register: "https://www.alabamainteractive.org/sos/voter_registration/voterRegistrationWelcome.action",
    checkRegistration: "https://myinfo.alabamavotes.gov/VoterView/RegistrantSearch.do",
    moreInfo: "https://www.sos.alabama.gov/alabama-votes/voter/register-to-vote",
  },
  AR: {
    code: "AR",
    name: "Arkansas",
    isState: true,
    registrationType: "by-mail",
    electionWebsite: "https://www.sos.arkansas.gov/elections/",
    checkRegistration: "https://www.voterview.ar-nova.org/voterview",
    moreInfo: "https://www.sos.arkansas.gov/elections/voter-information/",
  },
  AS: {
    code: "AS",
    name: "American Samoa",
    isState: false,
    registrationType: "in-person",
    electionWebsite: "https://aselectionoffice.gov/",
    checkRegistration: "https://aselectionoffice.gov/status.php",
    moreInfo: "https://aselectionoffice.gov/node/3",
  },
  AZ: {
    code: "AZ",
    name: "Arizona",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://azsos.gov/elections",
    register: "https://servicearizona.com/VoterRegistration/selectLanguage",
    checkRegistration: "https://my.arizona.vote/WhereToVote.aspx?s=individual",
    moreInfo: "https://azsos.gov/elections/voters/registering-vote/registerupdate-vote",
  },
  CA: {
    code: "CA",
    name: "California",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.sos.ca.gov/elections",
    register: "https://registertovote.ca.gov/",
    checkRegistration: "https://voterstatus.sos.ca.gov/",
    moreInfo: "https://www.sos.ca.gov/elections/voting-resources/voting-california/registering-vote",
  },
  CO: {
    code: "CO",
    name: "Colorado",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.sos.state.co.us/pubs/elections/",
    register: "https://www.sos.state.co.us/voter/pages/pub/olvr/verifyNewVoter.xhtml",
    checkRegistration: "https://www.sos.state.co.us/voter/pages/pub/olvr/findVoterReg.xhtml",
    moreInfo: "https://www.coloradosos.gov/voter/pages/pub/home.xhtml",
  },
  CT: {
    code: "CT",
    name: "Connecticut",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://portal.ct.gov/sots",
    register: "https://voterregistration.ct.gov/OLVR/welcome.do",
    checkRegistration: "https://portaldir.ct.gov/sots/LookUp.aspx",
    moreInfo: "https://portal.ct.gov/SOTS/Election-Services/Voter-Information/Voter-Fact-Sheet",
  },
  DC: {
    code: "DC",
    name: "District of Columbia",
    isState: false,
    registrationType: "online",
    electionWebsite: "https://dcboe.org/",
    register: "https://vr.dcboe.org/213324797239968?agency_code=12",
    checkRegistration: "https://apps.dcboe.org/vrs",
    moreInfo: "https://www.dcboe.org/voters/register-to-vote/register-update-voter-registration",
  },
  DE: {
    code: "DE",
    name: "Delaware",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://elections.delaware.gov/index.shtml",
    register: "https://ivote.de.gov/VoterView/registrant/newregistrant",
    checkRegistration: "https://ivote.de.gov/VoterView",
    moreInfo: "https://elections.delaware.gov/voter/votereg.shtml",
  },
  FL: {
    code: "FL",
    name: "Florida",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://dos.myflorida.com/elections/",
    register: "https://registertovoteflorida.gov/eligibilityreactive",
    checkRegistration: "https://registration.elections.myflorida.com/CheckVoterStatus",
    moreInfo: "https://registertovoteflorida.gov/home",
  },
  GA: {
    code: "GA",
    name: "Georgia",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://sos.ga.gov/index.php/elections",
    register: "https://registertovote.sos.ga.gov/GAOLVR/welcome.do#no-back-button",
    checkRegistration: "https://mvp.sos.ga.gov/s/",
    moreInfo: "https://sos.ga.gov/elections-division-georgia-secretary-states-office",
  },
  GU: {
    code: "GU",
    name: "Guam",
    isState: false,
    registrationType: "online",
    electionWebsite: "https://gec.guam.gov/",
    register: "https://gec.guam.gov/register/",
    checkRegistration: "https://gec.guam.gov/validate/",
    moreInfo: "https://gec.guam.gov/",
  },
  HI: {
    code: "HI",
    name: "Hawaii",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://elections.hawaii.gov/",
    register: "https://olvr.hawaii.gov/",
    checkRegistration: "https://olvr.hawaii.gov/",
    moreInfo: "https://elections.hawaii.gov/voters/registration/",
  },
  IA: {
    code: "IA",
    name: "Iowa",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://sos.iowa.gov/",
    register: "https://mymvd.iowadot.gov/Account/Login?ReturnUrl=%2fVoterRegistration",
    checkRegistration: "https://sos.iowa.gov/elections/voterreg/regtovote/search.aspx",
    moreInfo: "https://sos.iowa.gov/elections/voterinformation/voterregistration.html",
  },
  ID: {
    code: "ID",
    name: "Idaho",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://idahovotes.gov/",
    register: "https://elections.sos.idaho.gov/ElectionLink/ElectionLink/ApplicationInstructions.aspx",
    checkRegistration: "https://elections.sos.idaho.gov/ElectionLink/ElectionLink/VoterSearch.aspx",
    moreInfo: "https://idahovotes.gov/voting/",
  },
  IL: {
    code: "IL",
    name: "Illinois",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.elections.il.gov/",
    register: "https://ova.elections.il.gov/",
    checkRegistration: "https://ova.elections.il.gov/RegistrationLookup.aspx",
    moreInfo: "https://www.elections.il.gov/Default.aspx",
  },
  IN: {
    code: "IN",
    name: "Indiana",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.in.gov/sos/elections/",
    register: "https://indianavoters.in.gov/",
    checkRegistration: "https://indianavoters.in.gov/",
    moreInfo: "https://www.in.gov/sos/elections/2403.htm",
  },
  KS: {
    code: "KS",
    name: "Kansas",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://sos.ks.gov/elections/elections.html",
    register: "https://www.kdor.ks.gov/Apps/VoterReg/Default.aspx",
    checkRegistration: "https://myvoteinfo.voteks.org/voterview/",
    moreInfo: "https://sos.ks.gov/elections/voter-information.html",
  },
  KY: {
    code: "KY",
    name: "Kentucky",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://elect.ky.gov/Pages/default.aspx",
    register: "https://vrsws.sos.ky.gov/ovrweb/",
    checkRegistration: "https://vrsws.sos.ky.gov/VIC/",
    moreInfo: "https://elect.ky.gov/Resources/Pages/Registration.aspx",
  },
  LA: {
    code: "LA",
    name: "Louisiana",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.sos.la.gov/ElectionsAndVoting/Pages/default.aspx",
    register: "https://voterportal.sos.la.gov/VoterRegistration",
    checkRegistration: "https://voterportal.sos.la.gov/",
    moreInfo: "https://www.sos.la.gov/ElectionsAndVoting/RegisterToVote/Pages/default.aspx",
  },
  MA: {
    code: "MA",
    name: "Massachusetts",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.sec.state.ma.us/ele/eleidx.htm",
    register: "https://www.sec.state.ma.us/ovr/",
    checkRegistration: "https://www.sec.state.ma.us/VoterRegistrationSearch/MyVoterRegStatus.aspx",
    moreInfo: "https://www.sec.state.ma.us/divisions/elections/voter-resources/registering-to-vote.htm",
  },
  MD: {
    code: "MD",
    name: "Maryland",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://elections.maryland.gov/",
    register: "https://voterservices.elections.maryland.gov/OnlineVoterRegistration/InstructionsStep1",
    checkRegistration: "https://voterservices.elections.maryland.gov/VoterSearch",
    moreInfo: "https://www.elections.maryland.gov/voter_registration/application.html",
  },
  ME: {
    code: "ME",
    name: "Maine",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.maine.gov/sos/cec/elec/",
    register: "https://registertovote.sos.maine.gov/",
    checkRegistration: "https://maine.gov/sos/cec/elec/munic.html",
    moreInfo: "https://maine.gov/sos/cec/elec/voter-info/voterguide.html",
  },
  MI: {
    code: "MI",
    name: "Michigan",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.michigan.gov/sos/elections",
    register: "https://mvic.sos.state.mi.us/registervoter",
    checkRegistration: "https://mvic.sos.state.mi.us/Voter/Index",
    moreInfo: "https://mvic.sos.state.mi.us/",
  },
  MN: {
    code: "MN",
    name: "Minnesota",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.sos.state.mn.us/elections-voting/",
    register: "https://mnvotes.sos.state.mn.us/VoterRegistration/VoterRegistrationMain.aspx",
    checkRegistration: "https://mnvotes.sos.state.mn.us/VoterStatus.aspx",
    moreInfo: "https://www.sos.state.mn.us/elections-voting/register-to-vote/",
  },
  MO: {
    code: "MO",
    name: "Missouri",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.sos.mo.gov/elections",
    register: "https://s1.sos.mo.gov/elections/voterregistration/",
    checkRegistration: "https://voteroutreach.sos.mo.gov/portal/",
    moreInfo: "https://www.sos.mo.gov/elections/goVoteMissouri/register",
  },
  MP: {
    code: "MP",
    name: "Northern Mariana Islands",
    isState: false,
    registrationType: "in-person",
    electionWebsite: "https://www.votecnmi.gov.mp/",
    checkRegistration: "https://www.votecnmi.gov.mp/voter/are-you-registered-to-vote",
    moreInfo: "https://www.votecnmi.gov.mp/",
  },
  MS: {
    code: "MS",
    name: "Mississippi",
    isState: true,
    registrationType: "by-mail",
    electionWebsite: "https://www.sos.ms.gov/elections-voting/voter-registration-information",
    checkRegistration: "https://www.msegov.com/sos/voter_registration/amiregistered/Search",
    moreInfo: "https://www.sos.ms.gov/elections-voting/voter-registration-information",
  },
  MT: {
    code: "MT",
    name: "Montana",
    isState: true,
    registrationType: "by-mail",
    electionWebsite: "https://votemt.gov/",
    checkRegistration: "https://prodvoterportal.mt.gov/WhereToVote.aspx",
    moreInfo: "https://votemt.gov/",
  },
  NC: {
    code: "NC",
    name: "North Carolina",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.ncsbe.gov/voting",
    register: "https://www.ncdot.gov/dmv/offices-services/online/Pages/voter-registration-application.aspx",
    checkRegistration: "https://vt.ncsbe.gov/RegLkup/",
    moreInfo: "https://www.ncsbe.gov/registering/how-register",
  },
  ND: {
    code: "ND",
    name: "North Dakota",
    isState: true,
    registrationType: "not-needed",
    electionWebsite: "https://vip.sos.nd.gov/PortalList.aspx",
    checkRegistration: "https://vip.sos.nd.gov/WhereToVote.aspx?tab=&ptlPKID=&ptlhPKID=",
    moreInfo: "https://vip.sos.nd.gov/PortalList.aspx",
  },
  NE: {
    code: "NE",
    name: "Nebraska",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://sos.nebraska.gov/elections/2020-elections",
    register: "https://www.nebraska.gov/apps-sos-voter-registration/",
    checkRegistration: "https://www.votercheck.necvr.ne.gov/voterview",
    moreInfo: "https://sos.nebraska.gov/elections/voter-forms",
  },
  NH: {
    code: "NH",
    name: "New Hampshire",
    isState: true,
    registrationType: "by-mail",
    electionWebsite: "https://sos.nh.gov/home",
    checkRegistration: "https://app.sos.nh.gov/voterinformation",
    moreInfo: "https://www.sos.nh.gov/elections/voters/register-vote",
  },
  NJ: {
    code: "NJ",
    name: "New Jersey",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.state.nj.us/state/elections/index.shtml",
    register: "https://voter.svrs.nj.gov/register",
    checkRegistration: "https://voter.svrs.nj.gov/registration-check",
    moreInfo: "https://nj.gov/state/elections/voter-registration.shtml",
  },
  NM: {
    code: "NM",
    name: "New Mexico",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.sos.state.nm.us/voting-and-elections/",
    register: "https://portal.sos.state.nm.us/OVR/WebPages/InstructionsStep1.aspx",
    checkRegistration: "https://voterportal.servis.sos.state.nm.us/WhereToVote.aspx",
    moreInfo: "https://www.sos.state.nm.us/voting-and-elections/voter-information/voter-registration-information/",
  },
  NV: {
    code: "NV",
    name: "Nevada",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.nvsos.gov/sos/elections",
    register: "https://www.nvsos.gov/SOSVoterServices/start.aspx",
    checkRegistration: "https://www.nvsos.gov/votersearch/",
    moreInfo: "https://www.nvsos.gov/sos/elections/voters/registering-to-vote",
  },
  NY: {
    code: "NY",
    name: "New York",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.elections.ny.gov/",
    register: "https://dmv.ny.gov/more-info/electronic-voter-registration-application",
    checkRegistration: "https://voterlookup.elections.ny.gov/",
    moreInfo: "https://www.elections.ny.gov/votingregister.html",
  },
  OH: {
    code: "OH",
    name: "Ohio",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.sos.state.oh.us/elections/",
    register: "https://olvr.ohiosos.gov/",
    checkRegistration: "https://voterlookup.ohiosos.gov/voterlookup.aspx",
    moreInfo: "https://olvr.ohiosos.gov/",
  },
  OK: {
    code: "OK",
    name: "Oklahoma",
    isState: true,
    registrationType: "by-mail",
    electionWebsite: "https://www.ok.gov/elections/",
    checkRegistration: "https://okvoterportal.okelections.us/",
    moreInfo: "https://oklahoma.gov/elections/voter-registration/register-to-vote.html",
  },
  OR: {
    code: "OR",
    name: "Oregon",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://sos.oregon.gov/voting-elections/Pages/default.aspx",
    register: "https://secure.sos.state.or.us/orestar/vr/register.do",
    checkRegistration: "https://secure.sos.state.or.us/orestar/vr/showVoterSearch.do?lang=eng&source=SOS",
    moreInfo: "https://sos.oregon.gov/voting/Pages/registration.aspx",
  },
  PA: {
    code: "PA",
    name: "Pennsylvania",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.pa.gov/guides/voting-and-elections/",
    register: "https://www.pavoterservices.pa.gov/Pages/VoterRegistrationApplication.aspx",
    checkRegistration: "https://www.pavoterservices.pa.gov/pages/voterregistrationstatus.aspx",
    moreInfo: "https://www.pa.gov/guides/voting-and-elections/#RegisteringtoVote",
  },
  PR: {
    code: "PR",
    name: "Puerto Rico",
    isState: false,
    registrationType: "online",
    electionWebsite: "https://ww2.ceepur.org/Home/Index?aspxerrorpath=/es-pr/Paginas/default.aspx",
    register: "https://ere.ceepur.org/",
    checkRegistration: "https://consulta.ceepur.org/",
    moreInfo: "https://ww2.ceepur.org/es-pr/Paginas/cee-english.aspx",
  },
  RI: {
    code: "RI",
    name: "Rhode Island",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://elections.ri.gov/",
    register: "https://vote.sos.ri.gov/Home/RegistertoVote",
    checkRegistration: "https://vote.sos.ri.gov/Home/UpdateVoterRecord?ActiveFlag=0",
    moreInfo: "https://vote.sos.ri.gov/Voter/RegisterToVote",
  },
  SC: {
    code: "SC",
    name: "South Carolina",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.scvotes.gov/",
    register: "https://info.scvotes.sc.gov/eng/ovr/start.aspx",
    checkRegistration: "https://info.scvotes.sc.gov/eng/voterinquiry/VoterInformationRequest.aspx?PageMode=VoterInfo",
    moreInfo: "https://scvotes.gov/voters/register-to-vote/",
  },
  SD: {
    code: "SD",
    name: "South Dakota",
    isState: true,
    registrationType: "by-mail",
    electionWebsite: "https://sdsos.gov/elections-voting/",
    checkRegistration: "https://vip.sdsos.gov/VIPLogin.aspx",
    moreInfo: "https://sdsos.gov/elections-voting/voting/register-to-vote/default.aspx",
  },
  TN: {
    code: "TN",
    name: "Tennessee",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://sos.tn.gov/elections",
    register: "https://ovr.govote.tn.gov/",
    checkRegistration: "https://tnmap.tn.gov/voterlookup/",
    moreInfo: "https://sos.tn.gov/products/elections/register-vote",
  },
  TX: {
    code: "TX",
    name: "Texas",
    isState: true,
    registrationType: "by-mail",
    electionWebsite: "https://www.votetexas.gov/index.html",
    checkRegistration: "https://teamrv-mvp.sos.texas.gov/MVP/mvp.do",
    moreInfo: "https://www.votetexas.gov/register-to-vote/index.html",
  },
  UT: {
    code: "UT",
    name: "Utah",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://elections.utah.gov/",
    register: "https://secure.utah.gov/voterreg/login.html?selection=REGISTER",
    checkRegistration: "https://votesearch.utah.gov/voter-search/search/search-by-voter/voter-info",
    moreInfo: "https://voteinfo.utah.gov/",
  },
  VA: {
    code: "VA",
    name: "Virginia",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.elections.virginia.gov/",
    register: "https://www.elections.virginia.gov/citizen-portal/",
    checkRegistration: "https://www.elections.virginia.gov/registration/view-your-info/",
    moreInfo: "https://www.elections.virginia.gov/registration/how-to-register/",
  },
  VI: {
    code: "VI",
    name: "U.S. Virgin Islands",
    isState: false,
    registrationType: "in-person",
    electionWebsite: "https://www.vivote.gov/voters/register-to-vote/",
    checkRegistration: "https://vivote.gov/voters/lookup/",
    moreInfo: "https://www.vivote.gov/voters/register-to-vote/",
  },
  VT: {
    code: "VT",
    name: "Vermont",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://sos.vermont.gov/elections/",
    register: "https://olvr.vermont.gov/",
    checkRegistration: "https://mvp.vermont.gov/",
    moreInfo: "https://sos.vermont.gov/elections/voters/registration/",
  },
  WA: {
    code: "WA",
    name: "Washington",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://www.sos.wa.gov/elections/",
    register: "https://voter.votewa.gov/WhereToVote.aspx",
    checkRegistration: "https://voter.votewa.gov/WhereToVote.aspx",
    moreInfo: "https://www.sos.wa.gov/elections/voters/",
  },
  WI: {
    code: "WI",
    name: "Wisconsin",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://elections.wi.gov/voters",
    register: "https://myvote.wi.gov/en-us/RegisterToVote",
    checkRegistration: "https://myvote.wi.gov/en-us/MyVoterInfo",
    moreInfo: "https://elections.wi.gov/Register",
  },
  WV: {
    code: "WV",
    name: "West Virginia",
    isState: true,
    registrationType: "online",
    electionWebsite: "https://sos.wv.gov/elections/Pages/default.aspx",
    register: "https://ovr.sos.wv.gov/Register/Landing",
    checkRegistration: "https://apps.sos.wv.gov/Elections/voter/amiregisteredtovote",
    moreInfo: "https://ovr.sos.wv.gov/Register/Landing",
  },
  WY: {
    code: "WY",
    name: "Wyoming",
    isState: true,
    registrationType: "by-mail",
    electionWebsite: "https://sos.wyo.gov/elections/state/registeringtovote.aspx",
    checkRegistration: "https://sos.wyo.gov/Elections/Docs/WYCountyClerks.pdf",
    moreInfo: "https://sos.wyo.gov/Elections/State/RegisteringToVote.aspx",
  },
};
